""" Created New EventLog 

Revision ID: b516baac5c5e
Revises: 455121eb9a0b
Create Date: 2023-02-20 19:55:51.030777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b516baac5c5e'
down_revision = '455121eb9a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_log')
    # ### end Alembic commands ###
